# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: roomdata.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eroomdata.proto\x12\x08roomdata\"\xf8\x01\n\x08RoomData\x12.\n\x07members\x18\x01 \x03(\x0b\x32\x1d.roomdata.RoomData.RoomMember\x12\x0f\n\x07\x66ield_2\x18\x02 \x01(\x05\x12\x0f\n\x07\x66ield_3\x18\x03 \x01(\x05\x12\x0f\n\x07\x66ield_4\x18\x04 \x01(\x05\x12\x15\n\rroom_capacity\x18\x05 \x01(\x05\x12\x0f\n\x07\x66ield_6\x18\x06 \x01(\x05\x12\x13\n\x07\x66ield_7\x18\x07 \x01(\x03\x42\x02\x30\x01\x12\x13\n\x07\x66ield_8\x18\x08 \x01(\x03\x42\x02\x30\x01\x1a\x37\n\nRoomMember\x12\x0c\n\x04wxid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\x05\x42\x08Z\x06../wcfb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'roomdata_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\006../wcf'
  _ROOMDATA.fields_by_name['field_7']._options = None
  _ROOMDATA.fields_by_name['field_7']._serialized_options = b'0\001'
  _ROOMDATA.fields_by_name['field_8']._options = None
  _ROOMDATA.fields_by_name['field_8']._serialized_options = b'0\001'
  _ROOMDATA._serialized_start=29
  _ROOMDATA._serialized_end=277
  _ROOMDATA_ROOMMEMBER._serialized_start=222
  _ROOMDATA_ROOMMEMBER._serialized_end=277
# @@protoc_insertion_point(module_scope)
